[package]
name = "Angine"
version = "0.1.0"
edition = "2021"

[dependencies]
glium = "0.35.0"
glutin-winit = "0.5.0"
image = "0.25.5"
imgui = "0.12.0"
imgui-glium-renderer = "0.13.0"
imgui-winit-support = "0.13.0"
winit = "0.30.9"
